# -*- coding: utf-8 -*-
"""Stock_Market.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QOUlAD6xj_xv5tDozrXMA8tlQfzt69m0
"""

import numpy as np
import matplotlib.pyplot as plt

# Initialization of the variables

mu = 0.001
sigma = 0.01
start_price = 5

# Generate the random seeds
np.random.seed(0)

# np.random.normal(loc=0.0, scale=1.0, size=None) draws random samples from a normal (Gaussian) distribution.
returns = np.random.normal(loc=mu, scale=sigma, size=100)

# .cumprod() returns cumulative products
price = start_price*(1+returns).cumprod()

plt.rcParams["figure.figsize"] = (15,7)
plt.plot(price)

